# Generated by Django 5.2.7 on 2025-10-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='authour',
            new_name='author',
        ),
    ]
